'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Loader2, ShieldCheck, Building2, ArrowLeft, Sparkles } from 'lucide-react';
import { Logo } from './Logo';

export function AuthForm({mode}:{mode:'login'|'signup'|'forgot'|'reset'}){
 const router=useRouter();
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState('');
 const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const [message,setMessage]=useState('');
 const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError('');setMessage('');const supabase=createClient();
  if(mode==='forgot'){const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/auth/callback?next=/reset-password`}); if(error)setError(error.message); else setMessage('Password reset instructions sent. Check your email.'); setLoading(false); return;}
  if(mode==='reset'){const {error}=await supabase.auth.updateUser({password}); if(error)setError(error.message); else {setMessage('Password updated. You can now log in.'); setTimeout(()=>router.push('/login'),900);} setLoading(false); return;}
  if(mode==='signup'){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name},emailRedirectTo:`${location.origin}/auth/callback?next=/dashboard`}}); if(error)setError(error.message); else {if(data.session) router.push('/dashboard'); else setMessage('Account created. Check your email to confirm your account.');} }
  else {
   const {data,error}=await supabase.auth.signInWithPassword({email,password});
   if(error)setError(error.message);
   else { const {data:profile}=await supabase.from('profiles').select('role').eq('id',data.user.id).maybeSingle(); if(profile?.role==='hospital_staff') router.push('/hospital'); else router.push('/dashboard'); router.refresh(); }
  }
  setLoading(false);
 };
 const title=mode==='login'?'Welcome back':mode==='signup'?'Create your safety account':mode==='forgot'?'Reset your password':'Choose a new password';
 const subtitle=mode==='login'?'Your emergency tools are one secure sign-in away.':mode==='signup'?'Set up your safety profile in a couple of minutes.':mode==='forgot'?'We will send a secure password reset link.':'Create a new password for your Sahayak account.';
 return <main className="min-h-screen px-5 py-8 sm:py-12"><div className="mx-auto grid min-h-[calc(100vh-6rem)] max-w-5xl items-center gap-8 lg:grid-cols-[.9fr_1.1fr]">
   <div className="hidden lg:block"><Link href="/" className="inline-flex items-center gap-2 text-sm text-slate-400 transition hover:text-cyan-200"><ArrowLeft size={16}/> Back to Sahayak</Link><div className="mt-14"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/5 px-4 py-2 text-xs font-bold text-cyan-200"><Sparkles size={14}/> SAFETY, SIMPLIFIED</div><h1 className="text-5xl font-black leading-tight tracking-[-.045em]">Your safety tools.<br/><span className="text-cyan-300">One secure place.</span></h1><p className="mt-5 max-w-md leading-7 text-slate-400">Access your Medical ID, trusted contacts, SOS flow, hospital finder and emergency guidance.</p></div></div>
   <div><div className="mb-5 lg:hidden"><Logo/></div><div className="card relative overflow-hidden p-7 sm:p-9"><div className="absolute -right-20 -top-20 h-48 w-48 rounded-full bg-cyan-300/10 blur-3xl"/><div className="relative"><div className="mb-7"><div className="mb-4 inline-flex h-11 w-11 items-center justify-center rounded-2xl border border-cyan-300/20 bg-cyan-300/10 text-cyan-200"><ShieldCheck/></div><h1 className="text-2xl font-black">{title}</h1><p className="mt-2 text-sm text-slate-400">{subtitle}</p></div><form onSubmit={submit} className="space-y-4">{mode==='signup'&&<div><label className="label">Full name</label><input className="field" value={name} onChange={e=>setName(e.target.value)} required /></div>} {mode!=='reset'&&<div><label className="label">Email</label><input className="field" type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></div>} {mode!=='forgot'&&<div><label className="label">{mode==='reset'?'New password':'Password'}</label><input className="field" type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} required /></div>}<button className="btn-primary w-full py-3.5" disabled={loading}>{loading?<Loader2 className="animate-spin" size={18}/>:null}{mode==='login'?'Login':mode==='signup'?'Create account':mode==='forgot'?'Send reset link':'Update password'}</button></form>{mode==='login'&&<div className="mt-5 flex items-center gap-3 rounded-2xl border border-cyan-300/10 bg-cyan-300/[.035] p-4 text-sm text-slate-400"><Building2 size={18} className="shrink-0 text-cyan-300"/><span><b className="text-slate-200">Hospital staff?</b> Verified hospital accounts open the Hospital Command Center.</span></div>}{error&&<p className="mt-4 rounded-xl border border-red-400/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</p>}{message&&<p className="mt-4 rounded-xl border border-cyan-300/15 bg-cyan-300/5 p-3 text-sm text-cyan-100">{message}</p>}<div className="mt-6 text-center text-sm text-slate-400">{mode==='login'?<><Link className="text-cyan-300 transition hover:text-white" href="/forgot-password">Forgot password?</Link><span className="mx-2 text-slate-600">·</span><Link className="text-cyan-300 transition hover:text-white" href="/signup">Create account</Link></>:mode==='signup'?<Link className="text-cyan-300 transition hover:text-white" href="/login">Already have an account? Login</Link>:<Link className="text-cyan-300 transition hover:text-white" href="/login">Back to login</Link>}</div></div></div></div>
 </div></main> }
