'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BookOpen, HeartPulse, LocateFixed, MapPin, Phone, Siren, UsersRound, Hospital } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { Toast } from '@/components/Toast';

type DashboardClientProps={userId:string;userName:string};
type DashboardCard={href:string;title:string;Icon:LucideIcon;sub:string};
export default function DashboardClient({userName}:DashboardClientProps){
 const [toast,setToast]=useState('');const [contacts,setContacts]=useState<any[]>([]);const [medical,setMedical]=useState<any>(null);
 useEffect(()=>{const load=async()=>{const s=createClient();const [{data:c},{data:m}]=await Promise.all([s.from('emergency_contacts').select('*').order('created_at',{ascending:false}),s.from('medical_ids').select('*').maybeSingle()]);setContacts(c||[]);setMedical(m)};load()},[]);
 const share=()=>{if(!navigator.geolocation){setToast('Geolocation is not supported by this browser.');return;}navigator.geolocation.getCurrentPosition(async p=>{const url=`https://www.google.com/maps?q=${p.coords.latitude},${p.coords.longitude}`;try{if(navigator.share){await navigator.share({title:'Sahayak emergency location',text:'My current Sahayak location',url});setToast('Share sheet opened.');return}}catch{}if(navigator.clipboard)await navigator.clipboard.writeText(url);setToast('Location link copied. Share it with a trusted contact.')},()=>setToast('Location permission was denied or unavailable.'))};
 const cards:DashboardCard[]=[{href:'/contacts',title:'Emergency Contacts',Icon:UsersRound,sub:`${contacts.length} saved`},{href:'/medical-id',title:'Medical ID',Icon:HeartPulse,sub:medical?'Profile completed':'Complete profile'},{href:'/hospitals',title:'Find Hospitals',Icon:Hospital,sub:'Availability & cost guidance'},{href:'/emergency',title:'Emergency Guides',Icon:BookOpen,sub:'Offline-ready content'},{href:'/emergency',title:'Emergency Numbers',Icon:Phone,sub:'India emergency info'}];
 return <>{toast&&<Toast message={toast} onClose={()=>setToast('')}/>}<div className="mx-auto max-w-7xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-blue">SAFETY DASHBOARD</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Good morning, {userName.split(' ')[0]}.</h1><p className="mt-2 text-slate-400">Your safety information and emergency network are ready.</p></div><div className="rounded-full border border-emerald-400/10 bg-emerald-400/5 px-4 py-2 text-xs text-emerald-300">● Profile secure</div></div>
 <div className="mt-8 grid gap-6 lg:grid-cols-[1.05fr_.95fr]"><div className="card relative overflow-hidden p-8 sm:p-10"><div className="absolute -right-20 -top-20 h-60 w-60 rounded-full bg-red-500/10 blur-3xl"/><p className="text-xs uppercase tracking-[.2em] text-slate-500">Emergency action</p><h2 className="mt-2 text-2xl font-black">Need urgent help?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-400">Confirm SOS to record the emergency, capture your location and automatically route the case to an available connected hospital when one is online.</p><Link href="/emergency" className="btn-danger mt-7"><Siren size={18}/>Emergency SOS<ArrowRight size={17}/></Link><div className="mt-6 flex flex-wrap gap-3 text-xs text-slate-500"><span className="rounded-full bg-white/5 px-3 py-2">Hospital network</span><span className="rounded-full bg-white/5 px-3 py-2">Confirmation required</span></div></div>
 <div className="card p-8"><div className="flex items-center gap-3"><div className="rounded-2xl bg-blue/10 p-3 text-blue"><LocateFixed/></div><div><p className="font-bold">Share your location</p><p className="text-xs text-slate-500">One-time browser permission</p></div></div><p className="mt-6 text-sm leading-6 text-slate-400">Share your current coordinates through your device share sheet or copy a Google Maps link.</p><button onClick={share} className="btn-primary mt-6 w-full"><MapPin size={17}/>Share current location</button></div></div>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(card=>{const Icon=card.Icon;return <Link key={card.title} href={card.href} className="card p-5 transition hover:-translate-y-1 hover:border-blue/20"><div className="flex items-center justify-between"><div className="rounded-xl bg-white/5 p-2.5 text-blue"><Icon size={19}/></div><ArrowRight size={16} className="text-slate-600"/></div><p className="mt-5 font-bold">{card.title}</p><p className="mt-1 text-xs text-slate-500">{card.sub}</p></Link>})}</div></div></>;
}
